export const citynames = [
    'BANNING',				
    'BEAUMONT',
    'BLYTHE',
    'CALIMESA',
    'CATHEDRAL CITY',
    'COACHELLA',
    'CORONA',
    'DESERT HOT SPRINGS',
    'HEMET',
    'INDIAN WELLS',
    'INDIO',
    'JURUPA VALLEY',
    'LA QUINTA',
    'LAKE ELSINORE',
    'MENIFEE',
    'MORENO VALLEY',
    'MURRIETA',
    'NORCO',
    'PALM DESERT',
    'PALM SPRINGS',
    'PERRIS',
    'RANCHO MIRAGE',
    'RIVERSIDE',
    'RIVERSIDE 2',
    'RIVERSIDE 1',
    'SAN JACINTO',
    'TEMECULA',
    'WILDOMAR',
    'UNINCORPORATED 1',
    'UNINCORPORATED 2',
    'UNINCORPORATED 3',
    'UNINCORPORATED 4',
    'UNINCORPORATED 5',
];

export const base = {
    'District': 0,
    'Age':	{
        'Youth (18-24)': { 'Interview':0, 'Observation':0 },
        'Children (<18)': { 'Interview':0, 'Observation':0 },
        'Adults (>24)': { 'Interview':0, 'Observation':0 },
        //'Elderly (62+)': { 'Interview':0, 'Observation':0 },
        'Unknown Age': { 'Interview':0, 'Observation':0 },
        'Total': { 'Interview':0, 'Observation':0 },
    },
    'Race':	{
        'Asian': { 'Interview':0, 'Observation':0 },
        'Black': { 'Interview':0, 'Observation':0 },
        'White': { 'Interview':0, 'Observation':0 },
        'American Indian': { 'Interview':0, 'Observation':0 },
        'Native Hawaiian': { 'Interview':0, 'Observation':0 },
        'Multiple Races': { 'Interview':0, 'Observation':0 },
        'Unknown Race': { 'Interview':0, 'Observation':0 },
        'Total': { 'Interview':0, 'Observation':0 },
    },
    'Ethinicity':	{
        'Hispanic': { 'Interview':0, 'Observation':0 },
        'NonHispanic': { 'Interview':0, 'Observation':0 },
        'Unknown Ethinicity': { 'Interview':0, 'Observation':0 },
        'Total': { 'Interview':0, 'Observation':0 },
    },
    'Gender':	{
        'Male': { 'Interview':0, 'Observation':0 },
        'Female': { 'Interview':0, 'Observation':0 },
        'Transgender': { 'Interview':0, 'Observation':0 },
        'Gender Non-Conforming': { 'Interview':0, 'Observation':0 },
        'Unknown Gender': { 'Interview':0, 'Observation':0 },
        'Total': { 'Interview':0, 'Observation':0 },
    },
    'Subpopulations':	{
        'Veteran Yes': { 'Interview':0, 'Observation':0 },
        'Veteran No': { 'Interview':0, 'Observation':0 },
        'Chronically Homeless': { 'Interview':0, 'Observation':0 },
        'Not Chronically Homeless': { 'Interview':0, 'Observation':0 },
        'Substance Abuse': { 'Interview':0, 'Observation':0 },
        'No Substance Abuse': { 'Interview':0, 'Observation':0 },
        'Unknown Substance Abuse': { 'Interview':0, 'Observation':0 },
        'PTSD': { 'Interview':0, 'Observation':0 },
        'No PTSD': { 'Interview':0, 'Observation':0 },
        'Unknown PTSD': { 'Interview':0, 'Observation':0 },
        'Mental Health Conditions': { 'Interview':0, 'Observation':0 },
        'No Mental Health Conditions': { 'Interview':0, 'Observation':0 },
        'Unknown Mental Health Conditions': { 'Interview':0, 'Observation':0 },
        'Physical Disability': { 'Interview':0, 'Observation':0 },
        'No Physical Disability': { 'Interview':0, 'Observation':0 },
        'Unknown Physical Disability': { 'Interview':0, 'Observation':0 },
        'Developmental Disability': { 'Interview':0, 'Observation':0 },
        'No Developmental Disability': { 'Interview':0, 'Observation':0 },
        'Unknown Developmental Disability': { 'Interview':0, 'Observation':0 },
        'Brain Injury': { 'Interview':0, 'Observation':0 },
        'No Brain Injury': { 'Interview':0, 'Observation':0 },
        'Unknown Brain Injury': { 'Interview':0, 'Observation':0 },
        'Victim of Domestic Violence': { 'Interview':0, 'Observation':0 },
        'Not Victim of Domestic Violence': { 'Interview':0, 'Observation':0 },
        'Unknown Victim of Domestic Violence': { 'Interview':0, 'Observation':0 },
        'AIDS or HIV': { 'Interview':0, 'Observation':0 },
        'No AIDS or HIV': { 'Interview':0, 'Observation':0 },
        'Unknown AIDS or HIV': { 'Interview':0, 'Observation':0 },
        'Jail Release 90 Days: Probation': { 'Interview':0, 'Observation':0 },
        'Jail Release 90 Days: Parole': { 'Interview':0, 'Observation':0 },
        'Jail Release 90 Days: Completed Sentence': { 'Interview':0, 'Observation':0 },
        'Jail Release 90 Days: (Unspecified)': { 'Interview':0, 'Observation':0 },
        'Jail Release 12 Months: Probation': { 'Interview':0, 'Observation':0 },
        'Jail Release 12 Months: Parole': { 'Interview':0, 'Observation':0 },
        'Jail Release 12 Months: Completed Sentence': { 'Interview':0, 'Observation':0 },
        'Jail Release 12 Months: (Unspecified)': { 'Interview':0, 'Observation':0 },
        'No Jail': { 'Interview':0, 'Observation':0 },
        'Unknown Jail': { 'Interview':0, 'Observation':0 },
        //'Families with Children': { 'Interview':0, 'Observation':0 },
        'Total': { 'Interview':0, 'Observation':0 },
    }
};