export const colors = [
    [],
    '#AFCBE0',
    [
        '#AFCBE0',
        '#9FC2C9',
    ],
    [
        '#AFCBE0',
        '#C3D2D5',
        '#9FC2C9',
    ],
    [
        '#BDF1FC',
        '#AFCBE0',
        '#C3D2D5',
        '#9FC2C9',
    ],
    [
        '#BDF1FC',
        '#AFCBE0',
        '#C3D2D5',
        '#78BECC',
        '#9FC2C9',
    ],
    [
        '#BDF1FC',
        '#AFCBE0',
        '#C3D2D5',
        '#78BECC',
        '#9FC2C9',
        '#D6F8FF',
    ],
    [
        '#73AEBA',
        '#BDF1FC',
        '#AFCBE0',
        '#C3D2D5',
        '#78BECC',
        '#9FC2C9',
        '#D6F8FF',
    ]
];