# Generated by Django 2.2.4 on 2019-08-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseholdsByCityInterview',
            new_name='HouseholdsByCityYearInterview',
        ),
    ]
