# Generated by Django 2.2.1 on 2019-07-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdsbyCity2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('totalHouseholds', models.IntegerField()),
                ('adultsOnly', models.IntegerField()),
                ('childrenOnly', models.IntegerField()),
                ('adultsAndChildren', models.IntegerField()),
            ],
        ),
    ]
