# Generated by Django 2.2.6 on 2019-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTableSubpopulations2019',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('subpopulation', models.CharField(max_length=100)),
                ('interview', models.IntegerField()),
                ('observation', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
