# Generated by Django 2.2.1 on 2019-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_householdsbycity2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubpopulationsByCity2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subpopulation', models.CharField(max_length=100)),
                ('interview', models.IntegerField()),
                ('observation', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PracticeApp',
        ),
    ]
