export const uvsSubpopOrder = [
    'Individuals',
    'Adults (≥25)',
    'Youth (18-24)',
    'Children (≤17)',
    'Unknown Ages',
    'Male',
    'Female',
    'Transgender',
    'Gender Non-Con',
    'Unknown Gender',
    'Hispanic',
    'NonHispanic',
    'Unknown Ethnicity',
    'Asian',
    'American Indian',
    'Black',
    'White',
    'Multiple Races',
    'Native Hawaiian',
    'Unknown Race',
    'Chronically Homeless',
    'Substance Abuse',
    'Veterans',
    'Pet Owners',
];